
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 22 2024 18:45:02 +07 (Mar 22 2024 11:45:02 UTC)

// Verification Directory fv/Bounce_flash 

module Bounce_flash(clk, reset, flick, lamps);
  input clk, reset, flick;
  output [15:0] lamps;
  wire clk, reset, flick;
  wire [15:0] lamps;
  wire [4:0] lamp_counter;
  wire [2:0] current_state;
  wire [2:0] blink_counter;
  wire flick_active, n_0, n_1, n_2, n_3, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_15, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_33, n_34;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_84, n_86, n_87, n_88;
  wire n_89, n_90, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_193, n_199, n_200, n_201;
  wire n_202, n_203, n_204;
  DFFHQX1 \lamps_reg[2] (.CK (clk), .D (n_181), .Q (lamps[2]));
  DFFHQX1 \lamps_reg[3] (.CK (clk), .D (n_180), .Q (lamps[3]));
  DFFHQX1 \lamps_reg[1] (.CK (clk), .D (n_178), .Q (lamps[1]));
  DFFHQX1 \lamps_reg[4] (.CK (clk), .D (n_177), .Q (lamps[4]));
  DFFHQX1 \lamps_reg[13] (.CK (clk), .D (n_166), .Q (lamps[13]));
  DFFHQX1 \lamps_reg[8] (.CK (clk), .D (n_165), .Q (lamps[8]));
  DFFHQX1 \lamps_reg[14] (.CK (clk), .D (n_167), .Q (lamps[14]));
  DFFHQX1 \lamps_reg[12] (.CK (clk), .D (n_175), .Q (lamps[12]));
  DFFHQX1 \lamps_reg[9] (.CK (clk), .D (n_171), .Q (lamps[9]));
  DFFHQX1 \lamps_reg[11] (.CK (clk), .D (n_176), .Q (lamps[11]));
  DFFHQX1 \lamps_reg[7] (.CK (clk), .D (n_170), .Q (lamps[7]));
  AO22X1 g8281__2398(.A0 (lamp_counter[4]), .A1 (n_151), .B0 (n_77),
       .B1 (n_142), .Y (n_182));
  NAND2X1 g8295__5107(.A (n_164), .B (n_179), .Y (n_181));
  NAND2X1 g8306__6260(.A (n_161), .B (n_179), .Y (n_180));
  NAND2X1 g8307__4319(.A (n_163), .B (n_179), .Y (n_178));
  OAI211X1 g8309__8428(.A0 (n_174), .A1 (n_159), .B0 (n_114), .C0
       (n_179), .Y (n_177));
  OAI211X1 g8311__5526(.A0 (n_145), .A1 (n_173), .B0 (n_172), .C0
       (n_116), .Y (n_176));
  OAI211X1 g8312__6783(.A0 (n_174), .A1 (n_173), .B0 (n_172), .C0
       (n_122), .Y (n_175));
  OAI211X1 g8313__3680(.A0 (n_147), .A1 (n_173), .B0 (n_169), .C0
       (n_121), .Y (n_171));
  OAI211X1 g8315__1617(.A0 (n_1), .A1 (n_106), .B0 (n_169), .C0
       (n_173), .Y (n_170));
  OAI221X1 g8288__2802(.A0 (n_156), .A1 (n_150), .B0 (lamp_counter[3]),
       .B1 (n_136), .C0 (n_130), .Y (n_168));
  DFFHQX1 \lamps_reg[6] (.CK (clk), .D (n_160), .Q (lamps[6]));
  OAI211X1 g8304__1705(.A0 (n_55), .A1 (n_173), .B0 (n_172), .C0
       (n_110), .Y (n_167));
  OAI211X1 g8305__5122(.A0 (n_10), .A1 (n_173), .B0 (n_172), .C0
       (n_125), .Y (n_166));
  OAI211X1 g8294__8246(.A0 (n_9), .A1 (n_173), .B0 (n_169), .C0
       (n_118), .Y (n_165));
  DFFHQX1 \lamps_reg[0] (.CK (clk), .D (n_153), .Q (lamps[0]));
  DFFHQX1 \lamps_reg[15] (.CK (clk), .D (n_154), .Q (lamps[15]));
  DFFHQX1 \lamps_reg[5] (.CK (clk), .D (n_149), .Q (lamps[5]));
  DFFHQX1 \lamps_reg[10] (.CK (clk), .D (n_157), .Q (lamps[10]));
  AOI21X1 g8316__7098(.A0 (lamps[2]), .A1 (n_193), .B0 (n_146), .Y
       (n_164));
  AOI21X1 g8322__6131(.A0 (lamps[1]), .A1 (n_162), .B0 (n_148), .Y
       (n_163));
  AOI22X1 g8327__1881(.A0 (n_19), .A1 (n_144), .B0 (lamps[3]), .B1
       (n_193), .Y (n_161));
  OAI211X1 g8317__5115(.A0 (n_53), .A1 (n_159), .B0 (n_169), .C0
       (n_115), .Y (n_160));
  OAI2BB1X1 g8310__7482(.A0N (lamp_counter[2]), .A1N (n_141), .B0
       (n_143), .Y (n_158));
  OAI211X1 g8329__4733(.A0 (n_81), .A1 (n_159), .B0 (n_172), .C0
       (n_113), .Y (n_157));
  OA21X1 g8319__6161(.A0 (n_156), .A1 (n_159), .B0 (n_152), .Y (n_179));
  OAI221X1 g8326__9315(.A0 (lamp_counter[0]), .A1 (n_134), .B0 (n_27),
       .B1 (n_138), .C0 (n_62), .Y (n_155));
  OAI211X1 g8325__9945(.A0 (n_66), .A1 (n_159), .B0 (n_172), .C0
       (n_117), .Y (n_154));
  OAI211X1 g8324__2883(.A0 (n_99), .A1 (n_159), .B0 (n_111), .C0
       (n_152), .Y (n_153));
  OAI21X1 g8308__2346(.A0 (n_156), .A1 (n_139), .B0 (n_150), .Y
       (n_151));
  OAI211X1 g8328__1666(.A0 (n_64), .A1 (n_159), .B0 (n_169), .C0
       (n_112), .Y (n_149));
  NOR2X1 g8330__7410(.A (n_147), .B (n_159), .Y (n_148));
  OR2X2 g8332__6417(.A (n_52), .B (n_159), .Y (n_173));
  AOI21X1 g8334__5477(.A0 (n_13), .A1 (n_145), .B0 (n_159), .Y (n_146));
  INVX1 g8342(.A (n_159), .Y (n_144));
  AOI211XL g8314__2398(.A0 (n_31), .A1 (n_142), .B0 (n_200), .C0
       (n_61), .Y (n_143));
  AOI21X1 g8318__5107(.A0 (lamp_counter[2]), .A1 (n_133), .B0 (n_141),
       .Y (n_150));
  OA21X4 g8346__6260(.A0 (n_103), .A1 (n_119), .B0 (n_127), .Y (n_159));
  DFFHQX1 \current_state_reg[1] (.CK (clk), .D (n_132), .Q
       (current_state[1]));
  OAI221X1 g8323__4319(.A0 (n_128), .A1 (n_139), .B0 (n_20), .B1
       (n_138), .C0 (n_129), .Y (n_140));
  OAI211X1 g8333__8428(.A0 (current_state[0]), .A1 (n_108), .B0
       (n_131), .C0 (n_120), .Y (n_137));
  OAI21X1 g8336__5526(.A0 (n_18), .A1 (n_139), .B0 (n_138), .Y (n_141));
  INVX1 g8337(.A (n_200), .Y (n_136));
  NOR2X1 g8339__6783(.A (n_133), .B (n_142), .Y (n_134));
  OAI211X1 g8335__3680(.A0 (n_3), .A1 (n_123), .B0 (n_131), .C0
       (n_109), .Y (n_132));
  NAND2X1 g8338__1617(.A (n_78), .B (n_142), .Y (n_130));
  NAND2X1 g8345__1705(.A (n_128), .B (n_142), .Y (n_129));
  OAI31X1 g8348__5122(.A0 (n_67), .A1 (n_95), .A2 (n_101), .B0 (reset),
       .Y (n_127));
  INVX1 g8347(.A (n_139), .Y (n_133));
  OAI2BB1X1 g8351__8246(.A0N (flick_active), .A1N (n_100), .B0 (n_107),
       .Y (n_126));
  NAND2X1 g8363__7098(.A (lamps[13]), .B (n_162), .Y (n_125));
  OAI211X1 g8344__6131(.A0 (n_24), .A1 (n_123), .B0 (n_40), .C0 (n_94),
       .Y (n_124));
  NAND2X1 g8366__1881(.A (lamps[12]), .B (n_193), .Y (n_122));
  NAND2X1 g8365__5115(.A (lamps[9]), .B (n_162), .Y (n_121));
  OA22X1 g8343__7482(.A0 (n_14), .A1 (n_123), .B0 (n_75), .B1 (n_119),
       .Y (n_120));
  NAND2X1 g8364__4733(.A (lamps[8]), .B (n_193), .Y (n_118));
  NAND2X4 g8349__9315(.A (n_105), .B (reset), .Y (n_139));
  NAND2X1 g8371__9945(.A (lamps[15]), .B (n_162), .Y (n_117));
  NAND2X1 g8368__2883(.A (lamps[11]), .B (n_193), .Y (n_116));
  NAND2X1 g8369__2346(.A (lamps[6]), .B (n_162), .Y (n_115));
  NAND2X1 g8370__1666(.A (lamps[4]), .B (n_193), .Y (n_114));
  NAND2X1 g8367__7410(.A (lamps[10]), .B (n_162), .Y (n_113));
  NAND2X1 g8372__6417(.A (lamps[5]), .B (n_193), .Y (n_112));
  NAND2X1 g8373__5477(.A (lamps[0]), .B (n_162), .Y (n_111));
  NAND2X1 g8374__2398(.A (lamps[14]), .B (n_193), .Y (n_110));
  NAND2BX1 g8350__5107(.AN (n_108), .B (n_58), .Y (n_109));
  AOI21X1 g8357__6260(.A0 (n_73), .A1 (n_98), .B0 (n_84), .Y (n_107));
  INVX1 g8378(.A (n_162), .Y (n_106));
  NOR2X2 g8353__4319(.A (n_86), .B (n_102), .Y (n_105));
  AOI21X1 g8356__8428(.A0 (n_103), .A1 (n_72), .B0 (n_102), .Y (n_104));
  NAND2X2 g8354__5526(.A (n_102), .B (reset), .Y (n_138));
  AOI2BB1X1 g8379__6783(.A0N (n_39), .A1N (n_46), .B0 (n_97), .Y
       (n_101));
  OAI21X1 g8361__3680(.A0 (n_90), .A1 (n_99), .B0 (n_98), .Y (n_100));
  AND2X1 g8359__1617(.A (n_79), .B (n_169), .Y (n_152));
  NAND2X1 g8355__1705(.A (n_96), .B (reset), .Y (n_123));
  NAND2BX1 g8358__5122(.AN (n_96), .B (reset), .Y (n_108));
  DFFHQX1 \blink_counter_reg[0] (.CK (clk), .D (n_93), .Q
       (blink_counter[0]));
  NOR2X4 g8360__8246(.A (n_95), .B (n_204), .Y (n_102));
  OAI2BB1X1 g8376__7098(.A0N (reset), .A1N (n_88), .B0 (n_131), .Y
       (n_98));
  NOR2X4 g8387__6131(.A (n_76), .B (n_92), .Y (n_97));
  AND2X2 g8377__1881(.A (n_94), .B (n_172), .Y (n_169));
  AOI211X2 g8362__5115(.A0 (n_17), .A1 (n_89), .B0 (n_87), .C0 (n_80),
       .Y (n_96));
  OAI2BB1X1 g8389__7482(.A0N (blink_counter[0]), .A1N (n_199), .B0
       (n_172), .Y (n_93));
  NAND2X1 g8381__4733(.A (n_82), .B (reset), .Y (n_94));
  NAND2X2 g8393__6161(.A (n_43), .B (n_202), .Y (n_92));
  NOR2X2 g8375__9945(.A (n_90), .B (n_89), .Y (n_95));
  AO21X1 g8386__2883(.A0 (n_48), .A1 (flick), .B0 (n_87), .Y (n_88));
  AOI211X2 g8394__2346(.A0 (flick_active), .A1 (n_56), .B0 (n_44), .C0
       (n_70), .Y (n_86));
  NOR3X1 g8384__6417(.A (flick_active), .B (n_90), .C (n_81), .Y
       (n_82));
  NAND2X1 g8390__5477(.A (n_51), .B (n_65), .Y (n_80));
  OAI21X1 g8392__2398(.A0 (n_49), .A1 (n_74), .B0 (reset), .Y (n_79));
  ADDHX1 g8383__5107(.A (lamp_counter[3]), .B (n_54), .CO (n_77), .S
       (n_78));
  OR2X1 g8400__4319(.A (n_201), .B (n_74), .Y (n_87));
  INVX1 g8406(.A (n_72), .Y (n_73));
  AO22X4 g8382__5526(.A0 (flick_active), .A1 (n_99), .B0 (n_57), .B1
       (n_37), .Y (n_89));
  INVX1 g8407(.A (n_69), .Y (n_70));
  AOI22X2 g8405__6783(.A0 (n_67), .A1 (n_45), .B0 (n_66), .B1 (n_63),
       .Y (n_68));
  AOI222X1 g8401__3680(.A0 (n_64), .A1 (n_47), .B0 (blink_counter[0]),
       .B1 (n_33), .C0 (lamp_counter[4]), .C1 (n_63), .Y (n_65));
  INVX1 g8408(.A (n_61), .Y (n_62));
  NAND2X2 g8418__1617(.A (n_41), .B (n_30), .Y (n_60));
  OR3X1 g8419__1705(.A (n_50), .B (n_25), .C (n_63), .Y (n_58));
  NAND2X1 g8411__5122(.A (n_57), .B (n_56), .Y (n_72));
  NOR2X1 g8397__8246(.A (lamp_counter[4]), .B (n_54), .Y (n_55));
  NOR2BX1 g8398__7098(.AN (n_52), .B (n_54), .Y (n_53));
  AOI21X1 g8403__6131(.A0 (n_50), .A1 (n_99), .B0 (n_49), .Y (n_51));
  OAI22X1 g8404__1881(.A0 (n_90), .A1 (n_28), .B0 (n_21), .B1 (n_34),
       .Y (n_48));
  NOR2BX1 g8413__5115(.AN (n_47), .B (n_119), .Y (n_61));
  NAND2X1 g8412__7482(.A (n_46), .B (n_45), .Y (n_69));
  INVX1 g8416(.A (n_43), .Y (n_44));
  OAI21X1 g8420__4733(.A0 (n_39), .A1 (n_67), .B0 (reset), .Y (n_40));
  NOR2X2 g8415__6161(.A (n_64), .B (n_75), .Y (n_84));
  INVX1 g8388(.A (n_37), .Y (n_81));
  NOR2X2 g8424__9945(.A (n_47), .B (n_46), .Y (n_36));
  AOI21X2 g8421__2883(.A0 (n_38), .A1 (n_47), .B0 (n_67), .Y (n_43));
  NAND2X4 g8423__2346(.A (n_26), .B (reset), .Y (n_172));
  NAND2X1 g8428__7410(.A (n_90), .B (n_34), .Y (n_56));
  NOR2X4 g8437__6417(.A (n_33), .B (n_201), .Y (n_41));
  OAI21X2 g8391__5477(.A0 (n_156), .A1 (n_23), .B0 (n_66), .Y (n_37));
  ADDHX1 g8409__2398(.A (lamp_counter[2]), .B (n_22), .CO (n_54), .S
       (n_31));
  CLKAND2X2 g8426__5107(.A (n_90), .B (n_103), .Y (n_30));
  AND2X2 g8429__6260(.A (n_57), .B (n_29), .Y (n_63));
  OR3X1 g8422__4319(.A (n_57), .B (n_90), .C (n_0), .Y (n_131));
  NOR2X1 g8436__8428(.A (n_64), .B (n_103), .Y (n_49));
  CLKINVX4 g8432(.A (n_99), .Y (n_45));
  NAND2X1 g8438__5526(.A (n_64), .B (reset), .Y (n_119));
  OR4X1 g8434__3680(.A (lamp_counter[1]), .B (n_27), .C (n_2), .D
       (n_5), .Y (n_28));
  NOR2BX1 g8425__1617(.AN (n_33), .B (blink_counter[0]), .Y (n_26));
  INVX1 g8441(.A (n_29), .Y (n_34));
  CLKAND2X3 g8439__2802(.A (n_52), .B (n_15), .Y (n_99));
  INVX1 g8450(.A (n_103), .Y (n_25));
  AND2X6 g8445__5122(.A (n_24), .B (n_50), .Y (n_46));
  AND2X2 g8447__8246(.A (current_state[2]), .B (n_50), .Y (n_67));
  NOR2X2 g8454__7098(.A (lamp_counter[2]), .B (n_22), .Y (n_23));
  OR4X1 g8433__6131(.A (lamp_counter[0]), .B (n_20), .C (n_156), .D
       (n_19), .Y (n_21));
  NOR2X1 g8456__1881(.A (n_22), .B (n_18), .Y (n_128));
  AOI21X1 g8435__5115(.A0 (lamp_counter[2]), .A1 (n_8), .B0
       (lamp_counter[4]), .Y (n_174));
  INVX3 g8442(.A (n_38), .Y (n_64));
  INVX1 g8451(.A (n_90), .Y (n_17));
  CLKAND2X3 g8448__7482(.A (current_state[0]), .B (n_39), .Y (n_29));
  AND2X2 g8446__4733(.A (n_14), .B (n_39), .Y (n_47));
  NAND2X4 g8458__6161(.A (current_state[0]), .B (n_11), .Y (n_103));
  INVX1 g8462(.A (n_22), .Y (n_13));
  AND2X1 g8453__9315(.A (n_66), .B (n_6), .Y (n_10));
  NOR2X4 g8470__9945(.A (n_3), .B (current_state[0]), .Y (n_50));
  NAND3X4 g8459__2883(.A (n_7), .B (n_24), .C (current_state[0]), .Y
       (n_90));
  NOR2X1 g8452__2346(.A (n_8), .B (n_19), .Y (n_9));
  NOR2X4 g8444__1666(.A (lamp_counter[2]), .B (n_8), .Y (n_15));
  NOR2X1 g8455__7410(.A (lamp_counter[1]), .B (n_19), .Y (n_147));
  AND3X4 g8457__6417(.A (current_state[2]), .B (n_7), .C
       (current_state[0]), .Y (n_33));
  NAND2X6 g8449__5477(.A (n_52), .B (n_6), .Y (n_38));
  INVX1 g8460(.A (n_52), .Y (n_5));
  INVX1 g8461(.A (n_19), .Y (n_145));
  NOR2X2 g8466__2398(.A (n_20), .B (n_27), .Y (n_22));
  INVX1 g8468(.A (n_8), .Y (n_18));
  NOR2X2 g8469__5107(.A (n_7), .B (current_state[2]), .Y (n_11));
  NOR2X4 g8471__6260(.A (n_7), .B (n_24), .Y (n_39));
  OR2X6 g8472__4319(.A (lamp_counter[0]), .B (lamp_counter[1]), .Y
       (n_8));
  NOR2X6 g8464__8428(.A (lamp_counter[3]), .B (lamp_counter[4]), .Y
       (n_52));
  CLKINVX4 g8475(.A (n_7), .Y (n_3));
  OR2XL g8465__6783(.A (lamp_counter[4]), .B (lamp_counter[2]), .Y
       (n_19));
  INVX1 g8474(.A (lamps[7]), .Y (n_1));
  INVX1 g8485(.A (reset), .Y (n_0));
  BUFX2 drc_buf_sp8518(.A (n_162), .Y (n_193));
  DFFX2 \lamp_counter_reg[2] (.CK (clk), .D (n_158), .Q
       (lamp_counter[2]), .QN (n_2));
  DFFX2 \lamp_counter_reg[1] (.CK (clk), .D (n_140), .Q
       (lamp_counter[1]), .QN (n_20));
  DFFX2 \lamp_counter_reg[4] (.CK (clk), .D (n_182), .Q
       (lamp_counter[4]), .QN (n_66));
  DFFX2 \current_state_reg[0] (.CK (clk), .D (n_137), .Q
       (current_state[0]), .QN (n_14));
  DFFX2 \lamp_counter_reg[0] (.CK (clk), .D (n_155), .Q
       (lamp_counter[0]), .QN (n_27));
  DFFX1 flick_active_reg(.CK (clk), .D (n_126), .Q (flick_active), .QN
       (n_57));
  DFFX4 \current_state_reg[2] (.CK (clk), .D (n_124), .Q
       (current_state[2]), .QN (n_24));
  DFFX2 \lamp_counter_reg[3] (.CK (clk), .D (n_168), .Q
       (lamp_counter[3]), .QN (n_156));
  NOR2BX2 g8541(.AN (n_11), .B (current_state[0]), .Y (n_201));
  AOI2BB1X2 g8542(.A0N (lamp_counter[4]), .A1N (n_34), .B0 (n_60), .Y
       (n_202));
  NAND3BX2 g8543(.AN (n_84), .B (n_68), .C (n_203), .Y (n_204));
  OA21X1 g3(.A0 (n_38), .A1 (n_103), .B0 (n_36), .Y (n_203));
  NOR2X1 g8414__8545(.A (n_38), .B (n_75), .Y (n_74));
  NAND2BX1 g8547(.AN (n_41), .B (reset), .Y (n_199));
  NAND2X4 g8430__8549(.A (flick_active), .B (n_29), .Y (n_75));
  AND2X1 g8352__8551(.A (n_104), .B (reset), .Y (n_142));
  NAND2X2 g8396__8553(.A (n_75), .B (n_69), .Y (n_76));
  NOR2BX1 g8555(.AN (n_15), .B (n_139), .Y (n_200));
  AND2X1 g8380__8557(.A (n_97), .B (reset), .Y (n_162));
  NAND2X2 g8463__8559(.A (lamp_counter[1]), .B (lamp_counter[2]), .Y
       (n_6));
  BUFX6 g8561(.A (current_state[1]), .Y (n_7));
endmodule

